name: cg_extensions
description: Fancy, yet basically useless extensions for dart language used internally at Code Growers s.r.o.
publish_to: "none"
version: 0.0.7
homepage: https://github.com/Code-Growers/cg_extensions

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: 2.0.0
  flutter_i18n: 0.32.4
  dart_extensions: 2.2.0
  dartx: 1.1.0
  fluttertoast: 8.2.1
  febu:
    git:
      url: https://github.com/Code-Growers/febu.git
      ref: null_safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  cg_analysis:
    git:
      url: https://github.com/Code-Growers/cg_analysis.git
      ref: master

flutter:
