name: cg_extensions
description: Fancy, yet basically useless extensions for dart language used internally at Code Growers s.r.o.
publish_to: 'none'
version: 0.0.1
author: Adam Kvasnicka
homepage: https://github.com/Code-Growers/cg_extensions

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: 1.2.0
  flutter_i18n: 0.20.1
  dart_extensions: 1.0.2
  fluttertoast: 7.1.6
  flutter_screenutil: 4.0.2+2
  febu:
    git:
      url: https://github.com/Code-Growers/febu.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  cg_analysis:
    git:
      url: https://github.com/Code-Growers/cg_analysis.git
      ref: master

flutter:
